version: "3.9"

services:

  worker:
    image: python:3.11-alpine
    container_name: task-worker
    restart: always
    network_mode: host
    volumes:
      - ./worker:/worker
      - certs:/certs
    environment:
      REDIS_URL: redis://RPI_TAILSCALE_IP:6379/0
      NODE_ID: ${NODE_ID}
    command: >
      sh -c "
      pip install celery redis &&
      celery -A worker worker
      --loglevel=info
      --queues=${NODE_QUEUE}
      "

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: always
    network_mode: host
    pid: host

  step-client:
    image: smallstep/step-cli
    container_name: step-client
    restart: unless-stopped
    network_mode: host
    volumes:
      - certs:/certs
    environment:
      CA_URL: https://RPI_TAILSCALE_IP:9000
      NODE_NAME: ${NODE_ID}
    entrypoint: >
      sh -c "
      step ca certificate $NODE_NAME /certs/node.crt /certs/node.key
      --provisioner node-provisioner
      "

volumes:
  certs:
